# Generated by Django 4.1 on 2022-08-31 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=11)),
                ('type', models.CharField(max_length=500)),
                ('lastCrop', models.DateField()),
                ('location', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lossCommunication.event')),
            ],
        ),
    ]
