# Generated by Django 4.1 on 2022-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossCommunication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
