# Generated by Django 4.1 on 2022-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossCommunication', '0002_alter_producer_cpf_alter_producer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='producer',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
